'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
'
Namespace FedExValidator
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AddressValidationServiceSoapBinding", [Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressValidationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private addressValidationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ShippingValidator.My.MySettings.Default.ShippingValidator_FedExValidator_AddressValidationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event addressValidationCompleted As addressValidationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("addressValidation", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function addressValidation(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")> ByVal AddressValidationRequest As AddressValidationRequest) As <System.Xml.Serialization.XmlElementAttribute("AddressValidationReply", [Namespace]:="http://fedex.com/ws/addressvalidation/v2")> AddressValidationReply
            Dim results() As Object = Me.Invoke("addressValidation", New Object() {AddressValidationRequest})
            Return CType(results(0),AddressValidationReply)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addressValidationAsync(ByVal AddressValidationRequest As AddressValidationRequest)
            Me.addressValidationAsync(AddressValidationRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addressValidationAsync(ByVal AddressValidationRequest As AddressValidationRequest, ByVal userState As Object)
            If (Me.addressValidationOperationCompleted Is Nothing) Then
                Me.addressValidationOperationCompleted = AddressOf Me.OnaddressValidationOperationCompleted
            End If
            Me.InvokeAsync("addressValidation", New Object() {AddressValidationRequest}, Me.addressValidationOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddressValidationOperationCompleted(ByVal arg As Object)
            If (Not (Me.addressValidationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addressValidationCompleted(Me, New addressValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressValidationRequest
        
        Private webAuthenticationDetailField As WebAuthenticationDetail
        
        Private clientDetailField As ClientDetail
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private requestTimestampField As Date
        
        Private optionsField As AddressValidationOptions
        
        Private addressesToValidateField() As AddressToValidate
        
        '''<remarks/>
        Public Property WebAuthenticationDetail() As WebAuthenticationDetail
            Get
                Return Me.webAuthenticationDetailField
            End Get
            Set
                Me.webAuthenticationDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientDetail() As ClientDetail
            Get
                Return Me.clientDetailField
            End Get
            Set
                Me.clientDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestTimestamp() As Date
            Get
                Return Me.requestTimestampField
            End Get
            Set
                Me.requestTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Options() As AddressValidationOptions
            Get
                Return Me.optionsField
            End Get
            Set
                Me.optionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressesToValidate")>  _
        Public Property AddressesToValidate() As AddressToValidate()
            Get
                Return Me.addressesToValidateField
            End Get
            Set
                Me.addressesToValidateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class WebAuthenticationDetail
        
        Private userCredentialField As WebAuthenticationCredential
        
        '''<remarks/>
        Public Property UserCredential() As WebAuthenticationCredential
            Get
                Return Me.userCredentialField
            End Get
            Set
                Me.userCredentialField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class WebAuthenticationCredential
        
        Private keyField As String
        
        Private passwordField As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class ParsedAddress
        
        Private parsedUrbanizationCodeField() As ParsedElement
        
        Private parsedStreetLineField() As ParsedElement
        
        Private parsedCityField() As ParsedElement
        
        Private parsedStateOrProvinceCodeField() As ParsedElement
        
        Private parsedPostalCodeField() As ParsedElement
        
        Private parsedCountryCodeField() As ParsedElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedUrbanizationCode() As ParsedElement()
            Get
                Return Me.parsedUrbanizationCodeField
            End Get
            Set
                Me.parsedUrbanizationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", GetType(ParsedElement), IsNullable:=false)>  _
        Public Property ParsedStreetLine() As ParsedElement()
            Get
                Return Me.parsedStreetLineField
            End Get
            Set
                Me.parsedStreetLineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedCity() As ParsedElement()
            Get
                Return Me.parsedCityField
            End Get
            Set
                Me.parsedCityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedStateOrProvinceCode() As ParsedElement()
            Get
                Return Me.parsedStateOrProvinceCodeField
            End Get
            Set
                Me.parsedStateOrProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedPostalCode() As ParsedElement()
            Get
                Return Me.parsedPostalCodeField
            End Get
            Set
                Me.parsedPostalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedCountryCode() As ParsedElement()
            Get
                Return Me.parsedCountryCodeField
            End Get
            Set
                Me.parsedCountryCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class ParsedElement
        
        Private nameField As String
        
        Private valueField As String
        
        Private changesField() As AddressValidationChangeType
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Changes")>  _
        Public Property Changes() As AddressValidationChangeType()
            Get
                Return Me.changesField
            End Get
            Set
                Me.changesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Public Enum AddressValidationChangeType
        
        '''<remarks/>
        APARTMENT_NUMBER_NOT_FOUND
        
        '''<remarks/>
        APARTMENT_NUMBER_REQUIRED
        
        '''<remarks/>
        NORMALIZED
        
        '''<remarks/>
        REMOVED_DATA
        
        '''<remarks/>
        BOX_NUMBER_REQUIRED
        
        '''<remarks/>
        NO_CHANGES
        
        '''<remarks/>
        MODIFIED_TO_ACHIEVE_MATCH
        
        '''<remarks/>
        STREET_RANGE_MATCH
        
        '''<remarks/>
        BOX_NUMBER_MATCH
        
        '''<remarks/>
        RR_OR_HC_MATCH
        
        '''<remarks/>
        CITY_MATCH
        
        '''<remarks/>
        POSTAL_CODE_MATCH
        
        '''<remarks/>
        RR_OR_HC_BOX_NUMBER_NEEDED
        
        '''<remarks/>
        FORMATTED_FOR_COUNTRY
        
        '''<remarks/>
        APO_OR_FPO_MATCH
        
        '''<remarks/>
        GENERAL_DELIVERY_MATCH
        
        '''<remarks/>
        FIELD_TRUNCATED
        
        '''<remarks/>
        UNABLE_TO_APPEND_NON_ADDRESS_DATA
        
        '''<remarks/>
        INSUFFICIENT_DATA
        
        '''<remarks/>
        HOUSE_OR_BOX_NUMBER_NOT_FOUND
        
        '''<remarks/>
        POSTAL_CODE_NOT_FOUND
        
        '''<remarks/>
        INVALID_COUNTRY
        
        '''<remarks/>
        SERVICE_UNAVAILABLE_FOR_ADDRESS
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class ProposedAddressDetail
        
        Private scoreField As String
        
        Private changesField() As AddressValidationChangeType
        
        Private residentialStatusField As ResidentialStatusType
        
        Private residentialStatusFieldSpecified As Boolean
        
        Private deliveryPointValidationField As DeliveryPointValidationType
        
        Private deliveryPointValidationFieldSpecified As Boolean
        
        Private companyNameField As String
        
        Private addressField As Address
        
        Private parsedCompanyNameField() As ParsedElement
        
        Private parsedAddressField As ParsedAddress
        
        Private removedNonAddressDataField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property Score() As String
            Get
                Return Me.scoreField
            End Get
            Set
                Me.scoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Changes")>  _
        Public Property Changes() As AddressValidationChangeType()
            Get
                Return Me.changesField
            End Get
            Set
                Me.changesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResidentialStatus() As ResidentialStatusType
            Get
                Return Me.residentialStatusField
            End Get
            Set
                Me.residentialStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ResidentialStatusSpecified() As Boolean
            Get
                Return Me.residentialStatusFieldSpecified
            End Get
            Set
                Me.residentialStatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeliveryPointValidation() As DeliveryPointValidationType
            Get
                Return Me.deliveryPointValidationField
            End Get
            Set
                Me.deliveryPointValidationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DeliveryPointValidationSpecified() As Boolean
            Get
                Return Me.deliveryPointValidationFieldSpecified
            End Get
            Set
                Me.deliveryPointValidationFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable:=false)>  _
        Public Property ParsedCompanyName() As ParsedElement()
            Get
                Return Me.parsedCompanyNameField
            End Get
            Set
                Me.parsedCompanyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParsedAddress() As ParsedAddress
            Get
                Return Me.parsedAddressField
            End Get
            Set
                Me.parsedAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemovedNonAddressData() As String
            Get
                Return Me.removedNonAddressDataField
            End Get
            Set
                Me.removedNonAddressDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Public Enum ResidentialStatusType
        
        '''<remarks/>
        UNDETERMINED
        
        '''<remarks/>
        BUSINESS
        
        '''<remarks/>
        RESIDENTIAL
        
        '''<remarks/>
        INSUFFICIENT_DATA
        
        '''<remarks/>
        UNAVAILABLE
        
        '''<remarks/>
        NOT_APPLICABLE_TO_COUNTRY
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Public Enum DeliveryPointValidationType
        
        '''<remarks/>
        CONFIRMED
        
        '''<remarks/>
        UNCONFIRMED
        
        '''<remarks/>
        UNAVAILABLE
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class Address
        
        Private streetLinesField() As String
        
        Private cityField As String
        
        Private stateOrProvinceCodeField As String
        
        Private postalCodeField As String
        
        Private urbanizationCodeField As String
        
        Private countryCodeField As String
        
        Private residentialField As Boolean
        
        Private residentialFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("StreetLines")>  _
        Public Property StreetLines() As String()
            Get
                Return Me.streetLinesField
            End Get
            Set
                Me.streetLinesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StateOrProvinceCode() As String
            Get
                Return Me.stateOrProvinceCodeField
            End Get
            Set
                Me.stateOrProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UrbanizationCode() As String
            Get
                Return Me.urbanizationCodeField
            End Get
            Set
                Me.urbanizationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Residential() As Boolean
            Get
                Return Me.residentialField
            End Get
            Set
                Me.residentialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ResidentialSpecified() As Boolean
            Get
                Return Me.residentialFieldSpecified
            End Get
            Set
                Me.residentialFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressValidationResult
        
        Private addressIdField As String
        
        Private proposedAddressDetailsField() As ProposedAddressDetail
        
        '''<remarks/>
        Public Property AddressId() As String
            Get
                Return Me.addressIdField
            End Get
            Set
                Me.addressIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ProposedAddressDetails")>  _
        Public Property ProposedAddressDetails() As ProposedAddressDetail()
            Get
                Return Me.proposedAddressDetailsField
            End Get
            Set
                Me.proposedAddressDetailsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class NotificationParameter
        
        Private idField As String
        
        Private valueField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class Notification
        
        Private severityField As NotificationSeverityType
        
        Private sourceField As String
        
        Private codeField As String
        
        Private messageField As String
        
        Private localizedMessageField As String
        
        Private messageParametersField() As NotificationParameter
        
        '''<remarks/>
        Public Property Severity() As NotificationSeverityType
            Get
                Return Me.severityField
            End Get
            Set
                Me.severityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocalizedMessage() As String
            Get
                Return Me.localizedMessageField
            End Get
            Set
                Me.localizedMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MessageParameters")>  _
        Public Property MessageParameters() As NotificationParameter()
            Get
                Return Me.messageParametersField
            End Get
            Set
                Me.messageParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Public Enum NotificationSeverityType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        FAILURE
        
        '''<remarks/>
        NOTE
        
        '''<remarks/>
        SUCCESS
        
        '''<remarks/>
        WARNING
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressValidationReply
        
        Private highestSeverityField As NotificationSeverityType
        
        Private notificationsField() As Notification
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private replyTimestampField As Date
        
        Private addressResultsField() As AddressValidationResult
        
        '''<remarks/>
        Public Property HighestSeverity() As NotificationSeverityType
            Get
                Return Me.highestSeverityField
            End Get
            Set
                Me.highestSeverityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Notifications")>  _
        Public Property Notifications() As Notification()
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReplyTimestamp() As Date
            Get
                Return Me.replyTimestampField
            End Get
            Set
                Me.replyTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressResults")>  _
        Public Property AddressResults() As AddressValidationResult()
            Get
                Return Me.addressResultsField
            End Get
            Set
                Me.addressResultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class TransactionDetail
        
        Private customerTransactionIdField As String
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property CustomerTransactionId() As String
            Get
                Return Me.customerTransactionIdField
            End Get
            Set
                Me.customerTransactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class Localization
        
        Private languageCodeField As String
        
        Private localeCodeField As String
        
        '''<remarks/>
        Public Property LanguageCode() As String
            Get
                Return Me.languageCodeField
            End Get
            Set
                Me.languageCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocaleCode() As String
            Get
                Return Me.localeCodeField
            End Get
            Set
                Me.localeCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class VersionId
        
        Private serviceIdField As String
        
        Private majorField As Integer
        
        Private intermediateField As Integer
        
        Private minorField As Integer
        
        Public Sub New()
            MyBase.New
            Me.serviceIdField = "aval"
            Me.majorField = 2
            Me.intermediateField = 0
            Me.minorField = 0
        End Sub
        
        '''<remarks/>
        Public Property ServiceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Major() As Integer
            Get
                Return Me.majorField
            End Get
            Set
                Me.majorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Intermediate() As Integer
            Get
                Return Me.intermediateField
            End Get
            Set
                Me.intermediateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Minor() As Integer
            Get
                Return Me.minorField
            End Get
            Set
                Me.minorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressToValidate
        
        Private addressIdField As String
        
        Private companyNameField As String
        
        Private addressField As Address
        
        '''<remarks/>
        Public Property AddressId() As String
            Get
                Return Me.addressIdField
            End Get
            Set
                Me.addressIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class AddressValidationOptions
        
        Private verifyAddressesField As Boolean
        
        Private verifyAddressesFieldSpecified As Boolean
        
        Private checkResidentialStatusField As Boolean
        
        Private checkResidentialStatusFieldSpecified As Boolean
        
        Private maximumNumberOfMatchesField As String
        
        Private streetAccuracyField As AddressValidationAccuracyType
        
        Private streetAccuracyFieldSpecified As Boolean
        
        Private directionalAccuracyField As AddressValidationAccuracyType
        
        Private directionalAccuracyFieldSpecified As Boolean
        
        Private companyNameAccuracyField As AddressValidationAccuracyType
        
        Private companyNameAccuracyFieldSpecified As Boolean
        
        Private convertToUpperCaseField As Boolean
        
        Private convertToUpperCaseFieldSpecified As Boolean
        
        Private recognizeAlternateCityNamesField As Boolean
        
        Private recognizeAlternateCityNamesFieldSpecified As Boolean
        
        Private returnParsedElementsField As Boolean
        
        Private returnParsedElementsFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property VerifyAddresses() As Boolean
            Get
                Return Me.verifyAddressesField
            End Get
            Set
                Me.verifyAddressesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property VerifyAddressesSpecified() As Boolean
            Get
                Return Me.verifyAddressesFieldSpecified
            End Get
            Set
                Me.verifyAddressesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CheckResidentialStatus() As Boolean
            Get
                Return Me.checkResidentialStatusField
            End Get
            Set
                Me.checkResidentialStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CheckResidentialStatusSpecified() As Boolean
            Get
                Return Me.checkResidentialStatusFieldSpecified
            End Get
            Set
                Me.checkResidentialStatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>  _
        Public Property MaximumNumberOfMatches() As String
            Get
                Return Me.maximumNumberOfMatchesField
            End Get
            Set
                Me.maximumNumberOfMatchesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetAccuracy() As AddressValidationAccuracyType
            Get
                Return Me.streetAccuracyField
            End Get
            Set
                Me.streetAccuracyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StreetAccuracySpecified() As Boolean
            Get
                Return Me.streetAccuracyFieldSpecified
            End Get
            Set
                Me.streetAccuracyFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirectionalAccuracy() As AddressValidationAccuracyType
            Get
                Return Me.directionalAccuracyField
            End Get
            Set
                Me.directionalAccuracyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DirectionalAccuracySpecified() As Boolean
            Get
                Return Me.directionalAccuracyFieldSpecified
            End Get
            Set
                Me.directionalAccuracyFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyNameAccuracy() As AddressValidationAccuracyType
            Get
                Return Me.companyNameAccuracyField
            End Get
            Set
                Me.companyNameAccuracyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CompanyNameAccuracySpecified() As Boolean
            Get
                Return Me.companyNameAccuracyFieldSpecified
            End Get
            Set
                Me.companyNameAccuracyFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConvertToUpperCase() As Boolean
            Get
                Return Me.convertToUpperCaseField
            End Get
            Set
                Me.convertToUpperCaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ConvertToUpperCaseSpecified() As Boolean
            Get
                Return Me.convertToUpperCaseFieldSpecified
            End Get
            Set
                Me.convertToUpperCaseFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecognizeAlternateCityNames() As Boolean
            Get
                Return Me.recognizeAlternateCityNamesField
            End Get
            Set
                Me.recognizeAlternateCityNamesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecognizeAlternateCityNamesSpecified() As Boolean
            Get
                Return Me.recognizeAlternateCityNamesFieldSpecified
            End Get
            Set
                Me.recognizeAlternateCityNamesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReturnParsedElements() As Boolean
            Get
                Return Me.returnParsedElementsField
            End Get
            Set
                Me.returnParsedElementsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReturnParsedElementsSpecified() As Boolean
            Get
                Return Me.returnParsedElementsFieldSpecified
            End Get
            Set
                Me.returnParsedElementsFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Public Enum AddressValidationAccuracyType
        
        '''<remarks/>
        EXACT
        
        '''<remarks/>
        TIGHT
        
        '''<remarks/>
        MEDIUM
        
        '''<remarks/>
        LOOSE
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v2")>  _
    Partial Public Class ClientDetail
        
        Private accountNumberField As String
        
        Private meterNumberField As String
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MeterNumber() As String
            Get
                Return Me.meterNumberField
            End Get
            Set
                Me.meterNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub addressValidationCompletedEventHandler(ByVal sender As Object, ByVal e As addressValidationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addressValidationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AddressValidationReply
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AddressValidationReply)
            End Get
        End Property
    End Class
End Namespace
